on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

name: Docker Build - Multiarch
run-name: atheme:${{ github.event.inputs.release_tag }}

jobs:
  docker_build:
    name: "server:${{ github.event.inputs.release_tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ATHEME_VERSION=${{ github.event.inputs.release_tag }}
          tags: |
            dino82/atheme:${{ github.event.inputs.release_tag }}
            dino82/atheme:latest

